create table public."Favorites" (
  "Fave_id" bigint generated by default as identity primary key,
  "FLat" double precision,
  "FLong" double precision
);

create table public."PubUser" (
  "PUser_id" bigint generated by default as identity primary key,
  "FName" text,
  "Mname" text,
  "LName" text,
  "MobileNum" text,
  "Email" text,
  "Password" text,
  "Fave_id" bigint references public."Favorites" ("Fave_id")
);

alter table public."Favorites" enable row level security;
alter table public."PubUser" enable row level security;
;
